name: ci
on:
  push:
    tags: [ "v*" ]
    branches: [ main, unstable ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: true
          go-version: 1.18.x
      - uses: actions/checkout@v2
      - name: run go mod
        run: go mod tidy && go build
